### ISSUE TITLE
Sign in with Google account feature request

### ISSUE THREAD

**Issue by PrathmeshMutke** [Harshal0902/Rudra#120]
## Is your feature request related to a problem? Please describe.
Adding google account sign in feature

## Describe the solution you'd like
After adding google sign in feature no need to write name, email etc.

**Comment by PrathmeshMutke** [comment]
LGM SOC 2021

**Comment by Harshal0902** [comment]
@PrathmeshMutke go for it

**Comment by PrathmeshMutke** [comment]
Help wanted

**Comment by ayushnau** [comment]
I want to do this please assign it to me

**Comment by Harshal0902** [comment]
@Ayush2020012016 go ahead

**Comment by ayushnau** [comment]
I need site privacy policy,terms of service support email and if possible the logo for the website and I thing right now there is no such things.

**Comment by Harshal0902** [comment]
@Ayush2020012016 you can use Firebase for implementing the google auth. I have enable the google auth.

**Comment by ayushnau** [comment]
Ah I have a little confusion  where do I place sign in button in front page or any where else.

**Comment by Harshal0902** [comment]
Place it inside the **English/Police/index.html** and **English/Public/index.html** file

**Comment by ayushnau** [comment]
the error is coming not because of code but because of domain we are using to run the site.
this is suggested solution and it will corrected from your firebase console.
 
{The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working. Add your domain (127.0.0.1) to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.}

**Comment by Harshal0902** [comment]
Even if I do so, the code is incomplete, its not redirecting to the home page, and and Google auth. is enable along with the domain. So please check the code again.

**Comment by ayushnau** [comment]
![gogglesigninerror](https://user-images.githubusercontent.com/78146753/128143634-6e1b8cfa-a77c-4e3a-86aa-7b8a50366fbd.png)

its showing same thing again after adding redirect code

**Comment by Harshal0902** [comment]
@Ayush2020012016 just add the redirection link, I will check this out
